image: openjdk:8-jdk-slim

stages:
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test and publish:
  stage: publish
  script:
    - chmod +x gradlew
    - ./gradlew test publish
