image: openjdk:8-jdk-slim

stages:
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew test

publish:
  stage: publish
  script:
    - chmod +x gradlew
    - ./gradlew publish
  only:
    - tags
